return {
  -- {
  --   "echasnovski/mini.files",
  --   event = { "VeryLazy" },
  --   init = function()
  --     vim.api.nvim_create_autocmd("BufEnter", {
  --       group = vim.api.nvim_create_augroup("Neotree_start_directory", { clear = true }),
  --       desc = "Start Neo-tree with directory",
  --       once = true,
  --       callback = function()
  --         if package.loaded["mini.files"] then
  --           return
  --         else
  --           local stats = vim.uv.fs_stat(vim.fn.argv(0))
  --           if stats and stats.type == "directory" then require "mini.files" end
  --         end
  --       end,
  --     })
  --   end,
  -- },
}
